### ISSUE TITLE
ScopeSim renamed spectrum_templates to source_templates

### ISSUE THREAD

**Issue by AWehrhahn** [AstarVienna/HowManyBloodyPhotons#1]
Hi,
the import in hmbp/main.py should be changed from spectrum_templates  to source_templates as the naming was changed in scopesim.

**Comment by astronomyk** [comment]
Thanks!
Do you mean this line
<https://github.com/AstarVienna/HowManyBloodyPhotons/blob/a38a41e0c4ba007119935ad102bc9ab7056ade41/hmbp/main.py#L8>
?
I guess I need to redeploy to Pypi then.

-------------------------------------
Kieran Leschinski
Department of Astrophysics
University of Vienna


Am Fr., 11. Nov. 2022 um 13:43 Uhr schrieb Ansgar Wehrhahn <
***@***.***>:

**Comment by astronomyk** [comment]
@AWehrhahn - this had been fixed in my local version, but this was 4 commits ahead of the PyPi version. I have uploaded a new version to PyPi (0.2.1) so this should work out of the box now.

Thanks for noticing it!
I'll close this issue now.
